### ISSUE TITLE
latex issues during cmake

### ISSUE THREAD

**Issue by taovcu** [Dantali0n/qemu-csd#1]
Running  "cmake --build ." of the first build section met a lot of latex issues.
Can latex related build commands be removed from the main build procedure to avoid issues? 

The following is part of the error log.

"""
kpathsea: Running mktextfm nullfont
/usr/share/texlive/texmf-dist/web2c/mktexnam: Could not map source abbreviation  for nullfont.
/usr/share/texlive/texmf-dist/web2c/mktexnam: Need to update ?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input nullfont
This is METAFONT, Version 2.7182818 (TeX Live 2020/Debian) (preloaded base=mf)

kpathsea: Running mktexmf nullfont
! I can't find file `nullfont'.
<*> ...four; mag:=1; ; nonstopmode; input nullfont
                                                  
Please type another input file name
! Emergency stop.
<*> ...four; mag:=1; ; nonstopmode; input nullfont
                                                  
Transcript written on mfput.log.
grep: nullfont.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input nullfont' failed to make nullfont.tfm.
/home/taolu/git/qemu-csd/zcsd/documentation/IEEEtran.cls:1090: Font \OT1/ptm/b/
it/24=nullfont not loadable: Metric (TFM) file not found.
<to be read again> 
                   \relax 
l.1090 \@IEEEtunefonts
                      
)
** ATTENTION: Overriding command lockouts (line 2).
(/home/taolu/git/qemu-csd/zcsd/documentation/adjustbox.sty

! LaTeX Error: File `xkeyval.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
/home/taolu/git/qemu-csd/zcsd/documentation/adjustbox.sty:23: Emergency stop.
<read *> 
         
l.23 \RequirePackage
                    {adjcalc}^^M
/home/taolu/git/qemu-csd/zcsd/documentation/adjustbox.sty:23:  ==> Fatal error 
occurred, no output PDF file produced!
Transcript written on documentation.log.
/usr/bin/texi2dvi: pdflatex exited with bad status, quitting.
gmake[2]: *** [zcsd/documentation/CMakeFiles/latex-prebuild.dir/build.make:77: zcsd/documentation/CMakeFiles/latex-prebuild] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2237: zcsd/documentation/CMakeFiles/latex-prebuild.dir/all] Error 2
gmake: *** [Makefile:160: all] Error 2

"""

**Comment by Dantali0n** [comment]
You need an extensive amount of LaTeX packages, for Arch these are `texlive-bin texlive-science texlive-publishers texlive-latexextra texlive-humanities` I believe for Ubuntu / Debian there is a `texlive-full` metapackage.

Alternatively you can disable documentation building through cmake with `DENABLE_DOCUMENTATION=off`

**Comment by Dantali0n** [comment]
Closing this issue because it has become stale, feel free to reply if it does not work still and I can re-open it again. If the problem persist please do not open a new issue instead.
